[package]
name = "libgreat"
version = "0.1.0"
edition = "2021"

[features]
default = [
]
nightly = []

# selects a minimal subset of error codes in order to reduce binary size
errno_minimal = []

[dependencies]
log = "=0.4.17"
zerocopy = { version = "=0.7.0-alpha.2", default-features = false }
